[package]
name = "kv"
version = "0.1.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.31"
thiserror = "1"
toml = "0.5"
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1", optional = true}
rmp-serde = {version = "0.14", optional = true}

[features]
json = ["serde_json"]
msgpack = ["rmp-serde"]
