[package]
name = "kv"
version = "0.4.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["key-value-store", "database", "lmdb"]
repository = "https://github.com/zshipko/rust-kv"
documentation = "https://docs.rs/kv"
description = "A simple embedded key value store for Rust"

[dependencies]
lmdb = { version = "0.8" }
serde_cbor = { version = "0.8", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
tempdir = "0.3"

[features]
default = []
with-serde = ["serde"]
cbor-value = ["with-serde", "serde_cbor"]
