[package]
name = "kv"
version = "0.2.1"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["key-value-store", "database", "lmdb"]
repository = "https://github.com/zshipko/rust-kv"
documentation = "https://docs.rs/kv"
description = "Easy embedded key/value stores for applications written in Rust"

[dependencies]
lmdb = { version = "0.8" }
