[package]
name = "kv"
version = "0.20.0"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.31"
thiserror = "1"
toml = "0.5"
serde = {version = "1", features = ["derive"]}
serde_json = {version = "1", optional = true}
rmp-serde = {version = "0.14", optional = true}
bincode = {version = "1.2", optional = true}

[features]
default = ["json-value", "msgpack-value", "bincode-value"]
json-value = ["serde_json"]
msgpack-value = ["rmp-serde"]
bincode-value = ["bincode"]
