[package]
name = "kv"
version = "0.5.1"
authors = ["Zach Shipko <zachshipko@gmail.com>"]
license = "ISC"
keywords = ["key-value-store", "database", "lmdb"]
repository = "https://github.com/zshipko/rust-kv"
documentation = "https://docs.rs/kv"
description = "An embedded key/value store for Rust"
readme = "README.md"

[dependencies]
lmdb = { version = "0.8" }
serde = { version = "1" }
serde_derive = { version = "1" }
toml = { version = "0.4" }
serde_cbor = { version = "0.8", optional = true }
serde_json = { version = "1", optional = true }
bincode = { version = "1", optional = true}

[features]
default = []
cbor-value = ["serde_cbor"]
json-value = ["serde_json"]
bincode-value = ["bincode"]
